### PR TITLE
test_e2e: fix to make ipv6 tests run correctly (or detect incompatible sysctl settings)

### PR DESCRIPTION
**Pull request by qabpea**
Added code that verify the host network settings and also code that set them if ci/cd is set.

Made delete of clusters used for test default behaviour
Small changes in ginko settings in test_run
Prepared for changes in how kind cluster is created

### CODE REVIEW

**Comment by qabpea** [comment]
Looks like ci/cd expects the cluster to not be removed. I will push an update that does not remove the cluster when ci-cd flag is set

**Comment by dougsland** [comment]
late for the game but lgtm

**Pull request merged**
