### PR TITLE
Remove duplicate function in e2e-test.sh

### PR DESCRIPTION
**Pull request by nerdalert**
Remove the duplicate function delete_kind_cluster in e2e-test.sh

Signed-off-by: Brent Salisbury <bsalisbu@redhat.com>

### CODE REVIEW

**Comment by nerdalert** [comment]
PTAL at your leisure @astoycos ty!

**Comment by astoycos** [comment]
Duplicated here -> https://github.com/kubernetes-sigs/kpng/pull/304/files#diff-cd71237151db4feb6730f8bad1be6f59506dbecf670f963512ebc7f0d02a8041R324 Thanks @nerdalert!

**Review by astoycos — APPROVED** [review]

**Comment by astoycos** [comment]
CC @jayunit100

**Review by nehaLohia27 — APPROVED** [review]

**Pull request merged**
