### PR TITLE
Set kubeProxyMode: none in test_e2e.sh

### LINKED ISSUE #425: Disable kube-proxy in CI e2e tests
The kind cluster created for e2e tests in CI doesn't seem to have its kube-proxy disabled (ref: https://github.com/kubernetes-sigs/kpng/blob/master/hack/test_e2e.sh#L228-L238), like it should be, which makes the tests unreliable.

### PR DESCRIPTION
**Pull request by jaehnri**
We weren't setting `kubeProxyMode: none` on test_e2e.sh's `kind: Cluster` file.
FIxes #425

### CODE REVIEW

**Comment by jayunit100** [comment]
can you check on why the ipv6 test are failing?

**Comment by jayunit100** [comment]
lgtm to me but lets make the tests pass

**Comment by friedrichwilken** [comment]
@jayunit100 @jaehnri can this be closed?

**Comment by jayunit100** [comment]
Ya

**Pull request closed without merging**
