### PR TITLE
hack: add dougsland to OWNERS

### PR DESCRIPTION
**Pull request by dougsland**
I have been involved in scripts behind hack/ dir.
If possible, please add me as reviewer and commiter.

Signed-off-by: Douglas Schilling Landgraf <dlandgra@redhat.com>

### CODE REVIEW

**Comment by knabben** [comment]
Doug has helping a lot in the CI both on refactoring and reviewing, +1 for adding him as owner on this module

/lgtm

**Comment by nehaLohia27** [comment]
yaa agree. Thanks @dougsland for doing the great job :)

**Review by nehaLohia27 — APPROVED** [review]

**Comment by nehaLohia27** [comment]
@dougsland Can you get added yourself as kubernetes-sigs org..  Currently this file is invalid due to not being part of kubernetes org.

**Pull request merged**
