### PR TITLE
Fail job if test suite fails

### PR DESCRIPTION
**Pull request by aojea**
Fixes: https://github.com/kubernetes-sigs/kpng/issues/400

### CODE REVIEW

**Comment by jayunit100** [comment]
after this lets then separate tests "sig network stable " tests from the "sig network kpng failing" tests so that its easy for us to know about regression

**Comment by jayunit100** [comment]
ha now we have to make it so that the bot merges it even though the tests fail i guess

**Comment by aojea** [comment]
You can skip and add Todo

**Comment by qabpea** [comment]
This has been fixed in PR #437, This PR can now be closed

**Comment by aojea** [comment]
Thanks Per

**Pull request closed without merging**
