### PR TITLE
FIx small typo in readme.md

### PR DESCRIPTION
**Pull request by yankay**
change cillium to cilium.

Signed-off-by: Kay Yan <kay.yan@daocloud.io>

### CODE REVIEW

**Comment by dougsland** [comment]
lgtm

**Comment by dougsland** [comment]
@yankay are you using kpng locally or preprod / prod? Any feedback to the community ?

**Comment by yankay** [comment]
> @yankay are you using kpng locally or preprod / prod? Any feedback to the community ?

Thanks @dougsland .
We are evaluating kpng. If we have feedback , we would send to community. :-)

**Pull request merged**
