### PR TITLE
Add replace for backends

### PR DESCRIPTION
**Pull request by papagalu**
go mod vendor will not pick up the code changes without the replace statements
@jayunit100  please also test to be 100% sure

### CODE REVIEW

**Comment by astoycos** [comment]
Hrm... Shouldn't `go workspaces` take care of this? @mcluseau possibly you need to run `go work sync` to pickup the new changes

**Comment by papagalu** [comment]
@astoycos 
im running go mod vendor, and it does not pick the backend changes, might be totally wrong tho

**Comment by astoycos** [comment]
Right with [go  workspaces](https://go.dev/doc/tutorial/workspaces) you shouldn't need to manually run `go mod vendor` in the `/cmd` directory 

Are your changes not pulled in when running `./hack/test_e2e.sh -i ipv4 -b ebpf -d` or something of the sort? 

Because If so it'd be a build script issue most likely, not something with the go-mod

**Comment by astoycos** [comment]
We got rid of these manual replace directives here https://github.com/kubernetes-sigs/kpng/commit/ece218f2a535bd88f7e3f738a948ccb31fc63334#diff-f1a968212f46fdc23571392dbada601265c55aec6360ae92e4020fcba94156b3L5

**Comment by papagalu** [comment]
i believe this is not needed, thank you @astoycos !!!

**Pull request closed without merging**
