### PR TITLE
Add dependency review enforcement action

### PR DESCRIPTION
**Pull request by jaehnri**
Add the dependency review enforcement action:

https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review

Signed-off-by: jaehnri [joao.henri.cr@gmail.com](mailto:joao.henri.cr@gmail.com)

### CODE REVIEW

**Comment by knabben** [comment]
@jaehnri can you follow the same standard of the other jobs in the name `dependency review` without the hyphen?

**Comment by jaehnri** [comment]
@knabben I've renamed it to "review" as workflows do not accept special characters in job names.

**Comment by knabben** [comment]
Do you mean the spaces it seems other jobs are using it, take a look in the unit tests file in the same gh folder

**Comment by knabben** [comment]
@jaehnri missed on this one but please next time squash the commits, normally we keep everything in 1 or max 3 commits with the proper context.

The bot do it automatically if you add the label `/label tide/merge-method-squash`

**Pull request merged**
