### PR TITLE
Replace J2 template with Go Template

### PR DESCRIPTION
**Pull request by ksankeerth**
Currently, J2 template is used to generate template for kpng DaemonSet yaml. To use J2, We need Python. As suggested in #347, this PR uses Go template and simple program to remove Python dependency.

Signed-off-by: shankeerthan-kasilingam <shankeerthan1995@gmail.com>

### CODE REVIEW

**Review by nehaLohia27 — APPROVED** [review]

**Comment by jayunit100** [comment]
just saw this thanks !!!!!!!!!!

**Comment by astoycos** [comment]
/assign 

Thanks so much @ksankeerth I will take  a look at this ASAP

**Comment by astoycos** [comment]
This lgtm I just want to run CI before merging

**Pull request merged**
