### PR TITLE
Add SHA to image tag

### PR DESCRIPTION
**Pull request by clearnicki**
This PR adds sha to image tag in E2E_K8S_version

Fixes # 510

### CODE REVIEW

**Comment by daman1807** [comment]
@clearnicki,
thank you for working on this, can you create a map of kind Kubernetes versions and corresponding sha digests? 
The SHA digest should be picked up automatically depending on the provided **E2E_K8S_VERSION**.

you refer kind release sections for list of versions:  https://github.com/kubernetes-sigs/kind/releases

**Comment by clearnicki** [comment]
@daman1807 thanks for the advice. Since this is a bash script - I did a case statement instead of map. Let me know if you would like any more changes or want something else.

**Comment by daman1807** [comment]
/lgtm
/approve

thanks!

**Pull request merged**
